#installing Streamlit (for web app UI), deepface for selfies emotion recognition, pillow - to handle images
import streamlit as st
from PIL import Image
from deepface import DeepFace
import random
import tempfile


st.title("🎬 Mood to Movie Recommender 🎭")

uploaded_file = st.file_uploader("Upload your selfie:", type=["jpg", "png"])

mood_to_movies = {
    "happy": [
        ("Singin’ in the Rain", "https://www.imdb.com/title/tt0045152/"),
        ("La La Land", "https://www.imdb.com/title/tt3783958/"),
        ("The Lego Movie", "https://www.imdb.com/title/tt1490017/"),
        ("Paddington 2", "https://www.imdb.com/title/tt4468740/"),
        ("Chef", "https://www.imdb.com/title/tt2883512/"),
        ("The Intouchables", "https://www.imdb.com/title/tt1675434/"),
        ("Mamma Mia!", "https://www.imdb.com/title/tt0795421/"),
        ("Crazy Rich Asians", "https://www.imdb.com/title/tt3104988/"),
        ("The Princess Bride", "https://www.imdb.com/title/tt0093779/"),
        ("School of Rock", "https://www.imdb.com/title/tt0332379/"),
        ("Ferris Bueller's Day Off", "https://www.imdb.com/title/tt0091042/"),
        ("Love Actually", "https://www.imdb.com/title/tt0314331/"),
        ("The Grand Budapest Hotel", "https://www.imdb.com/title/tt2278388/"),
        ("Finding Nemo", "https://www.imdb.com/title/tt0266543/"),
        ("Moana", "https://www.imdb.com/title/tt3521164/"),
        ("Up", "https://www.imdb.com/title/tt1049413/"),
        ("The Greatest Showman", "https://www.imdb.com/title/tt1485796/"),
        ("Toy Story", "https://www.imdb.com/title/tt0114709/"),
        ("Elf", "https://www.imdb.com/title/tt0319343/"),
        ("Zootopia", "https://www.imdb.com/title/tt2948356/"),
        ("The Secret Life of Pets", "https://www.imdb.com/title/tt2709768/"),
        ("Pitch Perfect", "https://www.imdb.com/title/tt1981677/"),
        ("Bridget Jones’s Diary", "https://www.imdb.com/title/tt0243155/"),
        ("Clueless", "https://www.imdb.com/title/tt0112697/"),
        ("10 Things I Hate About You", "https://www.imdb.com/title/tt0147800/"),
        ("Yes Man", "https://www.imdb.com/title/tt1068680/"),
        ("Lilo & Stitch", "https://www.imdb.com/title/tt0275847/"),
        ("Mamma Mia! Here We Go Again", "https://www.imdb.com/title/tt6911608/"),
        ("The Proposal", "https://www.imdb.com/title/tt1041829/"),
        ("Sing", "https://www.imdb.com/title/tt3470600/"),
        ("The Emperor’s New Groove", "https://www.imdb.com/title/tt0120917/"),
        ("Cool Runnings", "https://www.imdb.com/title/tt0106611/"),
        ("Legally Blonde", "https://www.imdb.com/title/tt0250494/"),
        ("Shrek", "https://www.imdb.com/title/tt0126029/"),
        ("Mean Girls", "https://www.imdb.com/title/tt0377092/"),
        ("The Parent Trap", "https://www.imdb.com/title/tt0120783/"),
        ("She’s the Man", "https://www.imdb.com/title/tt0454945/"),
        ("Enchanted", "https://www.imdb.com/title/tt0461770/"),
        ("Matilda", "https://www.imdb.com/title/tt0117008/"),
        ("Freaky Friday", "https://www.imdb.com/title/tt0322330/"),
        ("Happy Feet", "https://www.imdb.com/title/tt0366548/"),
        ("My Big Fat Greek Wedding", "https://www.imdb.com/title/tt0259446/"),
        ("Sister Act", "https://www.imdb.com/title/tt0105417/"),
        ("Little Miss Sunshine", "https://www.imdb.com/title/tt0449059/"),
        ("Kiki’s Delivery Service", "https://www.imdb.com/title/tt0097814/"),
        ("Paddington", "https://www.imdb.com/title/tt1109624/"),
        ("Wreck-It Ralph", "https://www.imdb.com/title/tt1772341/"),
        ("The Peanuts Movie", "https://www.imdb.com/title/tt2452042/"),
        ("Monsters, Inc.", "https://www.imdb.com/title/tt0198781/"),
        ("Jumanji: Welcome to the Jungle", "https://www.imdb.com/title/tt2283362/")
    ],
    "sad": [
        ("Inside Out", "https://www.imdb.com/title/tt2096673/"),
        ("The Pursuit of Happyness", "https://www.imdb.com/title/tt0454921/"),
        ("Manchester by the Sea", "https://www.imdb.com/title/tt4034228/"),
        ("Schindler’s List", "https://www.imdb.com/title/tt0108052/"),
        ("Blue Valentine", "https://www.imdb.com/title/tt1120985/"),
        ("My Girl", "https://www.imdb.com/title/tt0102492/"),
        ("The Green Mile", "https://www.imdb.com/title/tt0120689/"),
        ("Bridge to Terabithia", "https://www.imdb.com/title/tt0398808/"),
        ("Grave of the Fireflies", "https://www.imdb.com/title/tt0095327/"),
        ("Hachi: A Dog’s Tale", "https://www.imdb.com/title/tt1028532/"),
        ("Atonement", "https://www.imdb.com/title/tt0783233/"),
        ("The Fault in Our Stars", "https://www.imdb.com/title/tt2582846/"),
        ("Marley & Me", "https://www.imdb.com/title/tt0822832/"),
        ("Million Dollar Baby", "https://www.imdb.com/title/tt0405159/"),
        ("Beaches", "https://www.imdb.com/title/tt0094715/"),
        ("Steel Magnolias", "https://www.imdb.com/title/tt0098384/"),
        ("My Sister’s Keeper", "https://www.imdb.com/title/tt1078588/"),
        ("The Boy in the Striped Pajamas", "https://www.imdb.com/title/tt0914798/"),
        ("Requiem for a Dream", "https://www.imdb.com/title/tt0180093/"),
        ("Dancer in the Dark", "https://www.imdb.com/title/tt0168629/"),
        ("The Pianist", "https://www.imdb.com/title/tt0253474/"),
        ("Life Is Beautiful", "https://www.imdb.com/title/tt0118799/"),
        ("Leaving Las Vegas", "https://www.imdb.com/title/tt0113627/"),
        ("Philadelphia", "https://www.imdb.com/title/tt0107818/"),
        ("P.S. I Love You", "https://www.imdb.com/title/tt0431308/"),
        ("The Lovely Bones", "https://www.imdb.com/title/tt0380510/"),
        ("Pay It Forward", "https://www.imdb.com/title/tt0223897/"),
        ("Ghost", "https://www.imdb.com/title/tt0099653/"),
        ("My Left Foot", "https://www.imdb.com/title/tt0097937/"),
        ("Precious", "https://www.imdb.com/title/tt0929632/"),
        ("The Notebook", "https://www.imdb.com/title/tt0332280/"),
        ("12 Years a Slave", "https://www.imdb.com/title/tt2024544/"),
        ("Dear Zachary", "https://www.imdb.com/title/tt1152758/"),
        ("A Monster Calls", "https://www.imdb.com/title/tt3416532/"),
        ("Rabbit Hole", "https://www.imdb.com/title/tt0935075/"),
        ("Terms of Endearment", "https://www.imdb.com/title/tt0086425/"),
        ("Up", "https://www.imdb.com/title/tt1049413/"),
        ("Titanic", "https://www.imdb.com/title/tt0120338/"),
        ("Schindler’s List", "https://www.imdb.com/title/tt0108052/"),
        ("Room", "https://www.imdb.com/title/tt3170832/"),
        ("Lion", "https://www.imdb.com/title/tt3741834/"),
        ("Good Will Hunting", "https://www.imdb.com/title/tt0119217/"),
        ("A Walk to Remember", "https://www.imdb.com/title/tt0281358/"),
        ("Dead Poets Society", "https://www.imdb.com/title/tt0097165/"),
        ("Million Dollar Baby", "https://www.imdb.com/title/tt0405159/"),
        ("Finding Neverland", "https://www.imdb.com/title/tt0308644/"),
        ("Manchester by the Sea", "https://www.imdb.com/title/tt4034228/"),
        ("Armageddon", "https://www.imdb.com/title/tt0120591/"),
        ("Armageddon", "https://www.imdb.com/title/tt0120591/"),
        ("The Book Thief", "https://www.imdb.com/title/tt0816442/")
    ],
    "angry": [
        ("Gladiator", "https://www.imdb.com/title/tt0172495/"),
        ("John Wick", "https://www.imdb.com/title/tt2911666/"),
        ("The Dark Knight", "https://www.imdb.com/title/tt0468569/"),
        ("Mad Max: Fury Road", "https://www.imdb.com/title/tt1392190/"),
        ("Kill Bill: Vol. 1", "https://www.imdb.com/title/tt0266697/"),
        ("Fight Club", "https://www.imdb.com/title/tt0137523/"),
        ("Oldboy", "https://www.imdb.com/title/tt0364569/"),
        ("300", "https://www.imdb.com/title/tt0416449/"),
        ("Taken", "https://www.imdb.com/title/tt0936501/"),
        ("The Revenant", "https://www.imdb.com/title/tt1663202/"),
        ("Django Unchained", "https://www.imdb.com/title/tt1853728/"),
        ("The Equalizer", "https://www.imdb.com/title/tt0455944/"),
        ("Atomic Blonde", "https://www.imdb.com/title/tt2406566/"),
        ("Rambo: First Blood", "https://www.imdb.com/title/tt0083944/"),
        ("Logan", "https://www.imdb.com/title/tt3315342/"),
        ("Heat", "https://www.imdb.com/title/tt0113277/"),
        ("Sicario", "https://www.imdb.com/title/tt3397884/"),
        ("American History X", "https://www.imdb.com/title/tt0120586/"),
        ("Scarface", "https://www.imdb.com/title/tt0086250/"),
        ("Unforgiven", "https://www.imdb.com/title/tt0105695/"),
        ("Inglourious Basterds", "https://www.imdb.com/title/tt0361748/"),
        ("The Punisher", "https://www.imdb.com/title/tt0330793/"),
        ("Kill Bill: Vol. 2", "https://www.imdb.com/title/tt0378194/"),
        ("Law Abiding Citizen", "https://www.imdb.com/title/tt1197624/"),
        ("Falling Down", "https://www.imdb.com/title/tt0106856/"),
        ("V for Vendetta", "https://www.imdb.com/title/tt0434409/"),
        ("Man on Fire", "https://www.imdb.com/title/tt0328107/"),
        ("The Raid: Redemption", "https://www.imdb.com/title/tt1899353/"),
        ("Edge of Tomorrow", "https://www.imdb.com/title/tt1631867/"),
        ("Crank", "https://www.imdb.com/title/tt0479884/"),
        ("Sin City", "https://www.imdb.com/title/tt0401792/"),
        ("Wanted", "https://www.imdb.com/title/tt0493464/"),
        ("The Bourne Ultimatum", "https://www.imdb.com/title/tt0440963/"),
        ("Shoot 'Em Up", "https://www.imdb.com/title/tt0465602/"),
        ("Death Proof", "https://www.imdb.com/title/tt1028528/"),
        ("Run All Night", "https://www.imdb.com/title/tt2199571/"),
        ("Commando", "https://www.imdb.com/title/tt0088944/"),
        ("Hardcore Henry", "https://www.imdb.com/title/tt3072482/"),
        ("The Equalizer 2", "https://www.imdb.com/title/tt3766354/"),
        ("Sicario: Day of the Soldado", "https://www.imdb.com/title/tt5052474/"),
        ("Sabotage", "https://www.imdb.com/title/tt1742334/"),
        ("Den of Thieves", "https://www.imdb.com/title/tt1259528/"),
        ("The Hateful Eight", "https://www.imdb.com/title/tt3460252/"),
        ("The Boondock Saints", "https://www.imdb.com/title/tt0144117/"),
        ("Wanted", "https://www.imdb.com/title/tt0493464/"),
        ("Bad Boys", "https://www.imdb.com/title/tt0112442/"),
        ("Crank: High Voltage", "https://www.imdb.com/title/tt1121931/"),
        ("The Accountant", "https://www.imdb.com/title/tt2140479/"),
        ("Wrath of Man", "https://www.imdb.com/title/tt11083552/"),
        ("Nobody", "https://www.imdb.com/title/tt7888964/")
    ],
        "surprise": [
        ("Inception", "https://www.imdb.com/title/tt1375666/"),
        ("The Prestige", "https://www.imdb.com/title/tt0482571/"),
        ("The Sixth Sense", "https://www.imdb.com/title/tt0167404/"),
        ("Gone Girl", "https://www.imdb.com/title/tt2267998/"),
        ("Memento", "https://www.imdb.com/title/tt0209144/"),
        ("Shutter Island", "https://www.imdb.com/title/tt1130884/"),
        ("Se7en", "https://www.imdb.com/title/tt0114369/"),
        ("Parasite", "https://www.imdb.com/title/tt6751668/"),
        ("Fight Club", "https://www.imdb.com/title/tt0137523/"),
        ("Primal Fear", "https://www.imdb.com/title/tt0117381/"),
        ("The Others", "https://www.imdb.com/title/tt0230600/"),
        ("The Usual Suspects", "https://www.imdb.com/title/tt0114814/"),
        ("The Game", "https://www.imdb.com/title/tt0119174/"),
        ("Donnie Darko", "https://www.imdb.com/title/tt0246578/"),
        ("The Machinist", "https://www.imdb.com/title/tt0361862/"),
        ("Oldboy", "https://www.imdb.com/title/tt0364569/"),
        ("Arrival", "https://www.imdb.com/title/tt2543164/"),
        ("Coherence", "https://www.imdb.com/title/tt2866360/"),
        ("Gone Baby Gone", "https://www.imdb.com/title/tt0452623/"),
        ("Lucky Number Slevin", "https://www.imdb.com/title/tt0425210/"),
        ("Enemy", "https://www.imdb.com/title/tt2316411/"),
        ("Predestination", "https://www.imdb.com/title/tt2397535/"),
        ("Triangle", "https://www.imdb.com/title/tt1187064/"),
        ("Secret Window", "https://www.imdb.com/title/tt0363988/"),
        ("Identity", "https://www.imdb.com/title/tt0309698/"),
        ("Before I Go to Sleep", "https://www.imdb.com/title/tt1726592/"),
        ("Shutter", "https://www.imdb.com/title/tt0482599/"),
        ("Orphan", "https://www.imdb.com/title/tt1148204/"),
        ("The Skeleton Key", "https://www.imdb.com/title/tt0397101/"),
        ("The Others", "https://www.imdb.com/title/tt0230600/"),
        ("Perfect Stranger", "https://www.imdb.com/title/tt0457430/"),
        ("Secret in Their Eyes", "https://www.imdb.com/title/tt1741273/"),
        ("Basic Instinct", "https://www.imdb.com/title/tt0103772/"),
        ("Gone in 60 Seconds", "https://www.imdb.com/title/tt0187078/"),
        ("The Departed", "https://www.imdb.com/title/tt0407887/"),
        ("Black Swan", "https://www.imdb.com/title/tt0947798/"),
        ("Zodiac", "https://www.imdb.com/title/tt0443706/"),
        ("Shutter Island", "https://www.imdb.com/title/tt1130884/"),
        ("Split", "https://www.imdb.com/title/tt4972582/"),
        ("Us", "https://www.imdb.com/title/tt6857112/"),
        ("Ex Machina", "https://www.imdb.com/title/tt0470752/"),
        ("Hereditary", "https://www.imdb.com/title/tt7784604/"),
        ("The Invitation", "https://www.imdb.com/title/tt2400463/"),
        ("The Invisible Man", "https://www.imdb.com/title/tt1051906/"),
        ("The Mist", "https://www.imdb.com/title/tt0884328/"),
        ("The Others", "https://www.imdb.com/title/tt0230600/"),
        ("Tenet", "https://www.imdb.com/title/tt6723592/"),
        ("Old", "https://www.imdb.com/title/tt10954600/"),
        ("Knives Out", "https://www.imdb.com/title/tt8946378/"),
        ("The Prestige", "https://www.imdb.com/title/tt0482571/")
    ],
    "fear": [
        ("Get Out", "https://www.imdb.com/title/tt5052448/"),
        ("A Quiet Place", "https://www.imdb.com/title/tt6644200/"),
        ("The Conjuring", "https://www.imdb.com/title/tt1457767/"),
        ("Hereditary", "https://www.imdb.com/title/tt7784604/"),
        ("The Exorcist", "https://www.imdb.com/title/tt0070047/"),
        ("It", "https://www.imdb.com/title/tt1396484/"),
        ("The Babadook", "https://www.imdb.com/title/tt2321549/"),
        ("Psycho", "https://www.imdb.com/title/tt0054215/"),
        ("Insidious", "https://www.imdb.com/title/tt1591095/"),
        ("The Ring", "https://www.imdb.com/title/tt0298130/"),
        ("The Shining", "https://www.imdb.com/title/tt0081505/"),
        ("The Blair Witch Project", "https://www.imdb.com/title/tt0185937/"),
        ("Sinister", "https://www.imdb.com/title/tt1922777/"),
        ("The Descent", "https://www.imdb.com/title/tt0435625/"),
        ("The Witch", "https://www.imdb.com/title/tt4263482/"),
        ("Us", "https://www.imdb.com/title/tt6857112/"),
        ("Paranormal Activity", "https://www.imdb.com/title/tt1179904/"),
        ("The Texas Chain Saw Massacre", "https://www.imdb.com/title/tt0072271/"),
        ("Halloween", "https://www.imdb.com/title/tt0077651/"),
        ("It Follows", "https://www.imdb.com/title/tt3235888/"),
        ("The Others", "https://www.imdb.com/title/tt0230600/"),
        ("The Grudge", "https://www.imdb.com/title/tt0391198/"),
        ("Saw", "https://www.imdb.com/title/tt0387564/"),
        ("Annabelle", "https://www.imdb.com/title/tt3322940/"),
        ("Insidious: Chapter 2", "https://www.imdb.com/title/tt2226417/"),
        ("The Conjuring 2", "https://www.imdb.com/title/tt3065204/"),
        ("Hostel", "https://www.imdb.com/title/tt0450278/"),
        ("The Cabin in the Woods", "https://www.imdb.com/title/tt1259521/"),
        ("The Omen", "https://www.imdb.com/title/tt0075005/"),
        ("The Silence of the Lambs", "https://www.imdb.com/title/tt0102926/"),
        ("Candyman", "https://www.imdb.com/title/tt0103919/"),
        ("The Haunting of Hill House", "https://www.imdb.com/title/tt6763664/"),
        ("The Nun", "https://www.imdb.com/title/tt5814060/"),
        ("Evil Dead", "https://www.imdb.com/title/tt1288558/"),
        ("Poltergeist", "https://www.imdb.com/title/tt0084516/"),
        ("The Amityville Horror", "https://www.imdb.com/title/tt0078767/"),
        ("Case 39", "https://www.imdb.com/title/tt0795351/"),
        ("1408", "https://www.imdb.com/title/tt0450385/"),
        ("Final Destination", "https://www.imdb.com/title/tt0195714/"),
        ("The Sixth Sense", "https://www.imdb.com/title/tt0167404/"),
        ("The Purge", "https://www.imdb.com/title/tt2184339/"),
        ("Gerald’s Game", "https://www.imdb.com/title/tt3748172/"),
        ("Bird Box", "https://www.imdb.com/title/tt2737304/"),
        ("Midsommar", "https://www.imdb.com/title/tt8772262/"),
        ("It Comes at Night", "https://www.imdb.com/title/tt4695012/"),
        ("The Invisible Man", "https://www.imdb.com/title/tt1051906/"),
        ("Lights Out", "https://www.imdb.com/title/tt4786282/"),
        ("Pet Sematary", "https://www.imdb.com/title/tt0837563/"),
        ("The Orphanage", "https://www.imdb.com/title/tt0464141/"),
        ("Hellraiser", "https://www.imdb.com/title/tt0093177/")
    ],
    "disgust": [
        ("Trainspotting", "https://www.imdb.com/title/tt0117951/"),
        ("Requiem for a Dream", "https://www.imdb.com/title/tt0180093/"),
        ("American Psycho", "https://www.imdb.com/title/tt0144084/"),
        ("Se7en", "https://www.imdb.com/title/tt0114369/"),
        ("Saw", "https://www.imdb.com/title/tt0387564/"),
        ("The Human Centipede", "https://www.imdb.com/title/tt1467304/"),
        ("Raw", "https://www.imdb.com/title/tt4954522/"),
        ("Mother!", "https://www.imdb.com/title/tt5109784/"),
        ("Irreversible", "https://www.imdb.com/title/tt0290673/"),
        ("Hostel", "https://www.imdb.com/title/tt0450278/"),
        ("Antichrist", "https://www.imdb.com/title/tt0870984/"),
        ("Martyrs", "https://www.imdb.com/title/tt1029234/"),
        ("The Neon Demon", "https://www.imdb.com/title/tt1974419/"),
        ("Salo, or the 120 Days of Sodom", "https://www.imdb.com/title/tt0073650/"),
        ("Cannibal Holocaust", "https://www.imdb.com/title/tt0078935/"),
        ("Henry: Portrait of a Serial Killer", "https://www.imdb.com/title/tt0099763/"),
        ("Serbian Film", "https://www.imdb.com/title/tt1273235/"),
        ("The Green Inferno", "https://www.imdb.com/title/tt2403021/"),
        ("Texas Chainsaw Massacre", "https://www.imdb.com/title/tt0072271/"),
        ("Tusk", "https://www.imdb.com/title/tt3099498/"),
        ("Pink Flamingos", "https://www.imdb.com/title/tt0069089/"),
        ("Ichi the Killer", "https://www.imdb.com/title/tt0296042/"),
        ("Grotesque", "https://www.imdb.com/title/tt1330054/"),
        ("Inside", "https://www.imdb.com/title/tt0856288/"),
        ("Bone Tomahawk", "https://www.imdb.com/title/tt2494362/"),
        ("Dead Alive", "https://www.imdb.com/title/tt0103873/"),
        ("Hostel: Part II", "https://www.imdb.com/title/tt0498353/"),
        ("High Tension", "https://www.imdb.com/title/tt0338095/"),
        ("Frontier(s)", "https://www.imdb.com/title/tt0814685/"),
        ("The House That Jack Built", "https://www.imdb.com/title/tt4003440/"),
        ("Begotten", "https://www.imdb.com/title/tt0099040/"),
        ("Baskin", "https://www.imdb.com/title/tt4935418/"),
        ("Maniac", "https://www.imdb.com/title/tt2103217/"),
        ("Calvaire", "https://www.imdb.com/title/tt0407621/"),
        ("The Girl Next Door", "https://www.imdb.com/title/tt0830558/"),
        ("A Serbian Film", "https://www.imdb.com/title/tt1273235/"),
        ("Hard Candy", "https://www.imdb.com/title/tt0424136/"),
        ("The Loved Ones", "https://www.imdb.com/title/tt1316536/"),
        ("The Devil's Rejects", "https://www.imdb.com/title/tt0395584/"),
        ("Inside (À l'intérieur)", "https://www.imdb.com/title/tt0856288/"),
        ("House of 1000 Corpses", "https://www.imdb.com/title/tt0251736/"),
        ("Kuso", "https://www.imdb.com/title/tt5692146/"),
        ("Antiviral", "https://www.imdb.com/title/tt2099556/"),
        ("The Void", "https://www.imdb.com/title/tt4255304/"),
        ("Tetsuo: The Iron Man", "https://www.imdb.com/title/tt0096251/"),
        ("V/H/S", "https://www.imdb.com/title/tt2105044/"),
        ("Tokyo Gore Police", "https://www.imdb.com/title/tt1262416/"),
        ("Martyrs", "https://www.imdb.com/title/tt1029234/"),
        ("The Sadness", "https://www.imdb.com/title/tt13872248/")
    ],
    "neutral": [
        ("Forrest Gump", "https://www.imdb.com/title/tt0109830/"),
        ("The Truman Show", "https://www.imdb.com/title/tt0120382/"),
        ("The Secret Life of Walter Mitty", "https://www.imdb.com/title/tt0359950/"),
        ("Cast Away", "https://www.imdb.com/title/tt0162222/"),
        ("The Curious Case of Benjamin Button", "https://www.imdb.com/title/tt0421715/"),
        ("The Hundred-Foot Journey", "https://www.imdb.com/title/tt2980648/"),
        ("Julie & Julia", "https://www.imdb.com/title/tt1135503/"),
        ("Amélie", "https://www.imdb.com/title/tt0211915/"),
        ("Big Fish", "https://www.imdb.com/title/tt0319061/"),
        ("The Terminal", "https://www.imdb.com/title/tt0362227/"),
        ("Life of Pi", "https://www.imdb.com/title/tt0454876/"),
        ("Finding Forrester", "https://www.imdb.com/title/tt0181536/"),
        ("The Bucket List", "https://www.imdb.com/title/tt0825232/"),
        ("Up in the Air", "https://www.imdb.com/title/tt1193138/"),
        ("Lost in Translation", "https://www.imdb.com/title/tt0335266/"),
        ("Moneyball", "https://www.imdb.com/title/tt1210166/"),
        ("Catch Me If You Can", "https://www.imdb.com/title/tt0264464/"),
        ("Good Will Hunting", "https://www.imdb.com/title/tt0119217/"),
        ("Erin Brockovich", "https://www.imdb.com/title/tt0195685/"),
        ("Jerry Maguire", "https://www.imdb.com/title/tt0116695/"),
        ("About Time", "https://www.imdb.com/title/tt2194499/"),
        ("The Holiday", "https://www.imdb.com/title/tt0457939/"),
        ("The Pursuit of Happyness", "https://www.imdb.com/title/tt0454921/"),
        ("Little Miss Sunshine", "https://www.imdb.com/title/tt0449059/"),
        ("Julie & Julia", "https://www.imdb.com/title/tt1135503/"),
        ("Chocolat", "https://www.imdb.com/title/tt0241303/"),
        ("Eat Pray Love", "https://www.imdb.com/title/tt0871426/"),
        ("Wild", "https://www.imdb.com/title/tt2305051/"),
        ("The Way", "https://www.imdb.com/title/tt1441912/"),
        ("The Best Exotic Marigold Hotel", "https://www.imdb.com/title/tt1412386/"),
        ("Brooklyn", "https://www.imdb.com/title/tt2381111/"),
        ("A Beautiful Day in the Neighborhood", "https://www.imdb.com/title/tt3224458/"),
        ("The Intern", "https://www.imdb.com/title/tt2361509/"),
        ("Chef", "https://www.imdb.com/title/tt2883512/"),
        ("Yes Man", "https://www.imdb.com/title/tt1068680/"),
        ("Amélie", "https://www.imdb.com/title/tt0211915/"),
        ("Julie & Julia", "https://www.imdb.com/title/tt1135503/"),
        ("The Hundred-Foot Journey", "https://www.imdb.com/title/tt2980648/"),
        ("Hector and the Search for Happiness", "https://www.imdb.com/title/tt1626146/"),
        ("The Peanut Butter Falcon", "https://www.imdb.com/title/tt4364194/"),
        ("Finding Nemo", "https://www.imdb.com/title/tt0266543/"),
        ("Moonrise Kingdom", "https://www.imdb.com/title/tt1748122/"),
        ("The Secret Life of Pets", "https://www.imdb.com/title/tt2709768/"),
        ("The Secret Life of Walter Mitty", "https://www.imdb.com/title/tt0359950/"),
        ("Little Women", "https://www.imdb.com/title/tt3281548/"),
        ("A Man Called Ove", "https://www.imdb.com/title/tt4080728/"),
        ("Julie & Julia", "https://www.imdb.com/title/tt1135503/"),
        ("Julie & Julia", "https://www.imdb.com/title/tt1135503/"),
        ("Julie & Julia", "https://www.imdb.com/title/tt1135503/")
    ]
}
if uploaded_file:
    img=Image.open(uploaded_file)
    st.image(img,caption="Uploaded Selfie",use_column_width=True)
    try:
        # Save uploaded_file to a temporary file
        with tempfile.NamedTemporaryFile(delete=False, suffix=".jpg") as tmp:
            tmp.write(uploaded_file.read())
            tmp_path = tmp.name
        result= DeepFace.analyze(img_path=uploaded_file,actions=['emotion'],enforce_detection=False)
        mood=result[0]['dominant_emotion']
        st.success(f"Your mood is detected as: {mood.capitalize()}**")
        mood_lower = mood.lower()
        movies_list = mood_to_movies.get(mood_lower, mood_to_movies["neutral"])
        chosen_movie = random.choice(movies_list)
        title, link = chosen_movie

        st.markdown("## 🎥 Recommended Movie:")
        st.markdown(f"- [{title}]({link})")
    except Exception as e:
        st.error(f"Error in emotion detection: {str(e)}")